@apiUrl = http://localhost:8081/notes
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6Impvcm1hQGdtYWlsLmNvbSIsIm5hbWUiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU4ODcwMzkyLCJleHAiOjE3NjE0NjIzOTJ9.VJKWy7_bBzRpxAB-SoAj-s0mkf_vTbDqiIT1SFtp66c

###

### Hämta alla notes för inloggade usern
GET {{apiUrl}}
Authorization: Bearer {{token}}

###

### Skapa en ny note
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My first note",
  "content": "This is some important content."

}


### Updatera Note med id
PUT {{apiUrl}}/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated note title",
  "content": "Updated content for the note."
}

###

### Radera note med id
DELETE {{apiUrl}}/1
Authorization: Bearer {{token}}
